encoding: utf-8

# SEO相关信息
title: 中森明菜出道40年歌曲作品全检索查询系统
description: JHrockice的博客
keywords: JHrockice,rockice,Blog,中森明菜,歌曲,akina,Akina,Nakamori,检索,查询,单曲,专辑,视频,歌姬,明菜
author: JHrockice
footerText: 'Copyright © JHrockice&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;'

# 这些不要动
permalink: /posts/:year/:month/:day/:title.html
kramdown:
  auto_ids: true
  input: GFM
  syntax_highlighter: rouge
exclude: ['CNAME', 'README.md', 'LICENSE', '_site', 'dist', 'Gemfile', 'Gemfile.lock', 'blog.sh']

# 域名配置
# baseurl配置,如果网站部署在根目录下的其他目录中，请设置为 /目录名
domainUrl: 'http://akinanakamori.info'
baseurl: ''

# 菜单
# 必填字段 title: '文本' url: '链接'
# 可选字段 target: '_blank' 新页面打开 
menu:
  - title: 说明
    url: /pages/about.html
  - title: 搜索
    url: /pages/search.html
  - title: 归类
    url: /pages/categories.html
